name: Perform Code Clean
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  clean-code:
    uses: laeubi/eclipse.platform.releng.aggregator/.github/workflows/cleanCode.yml@add_manifest_cleanup_profile
    with:
      author: Eclipse Equinox Bot <equinox-bot@eclipse.org>
      do-quickfix: false
      do-cleanups: true
      do-manifest: true
    secrets:
      token: ${{ secrets.EQUINOX_BOT_PAT }}
